# Generated by Django 3.2.5 on 2021-07-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('course_number', models.IntegerField(default='', max_length=10)),
                ('instructor_name', models.CharField(default='', max_length=50)),
                ('duration', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
            ],
        ),
    ]
